server:
  port: 8082

spring:
  application:
    name: shumeng-user-server
  cloud:
    config:
      uri: http://localhost:8888

mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: com.shumeng.mapper
